tracer:
   property: "I AM THE DEFAULT"
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: p0stgr@s
        url: jdbc:postgresql://localhost:5432/POSTGRESQL
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true                
license:
   dsc:
      prfx: Refresh Srvc
   dsa:
      prfx: In Arabic
resilience4j:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 1s
    thread-pool-bulkhead:
      instances:
        Organization-Service:
          coreThreadPoolSize: 10
          maxThreadPoolSize: 10
          queueCapacity: 5


  #  CIRCUITBREAKER:
  # -----------------
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 10
        eventConsumerBufferSize: 10
        
  # RATELIMITER
  # ------------------
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 1
        eventConsumerBufferSize: 100
  timelimiter:
    instances:
        Organization-Service:
         timeoutDuration: 2s
         cancelRunningFuture: true
