tracer:
   property: "I AM THE DEFAULT"
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: p0stgr@s
        url: jdbc:postgresql://localhost:5432/POSTGRESQL
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
license:
   dsc:
      prfx: QueriedFromDb
      